apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "api-gateway.name" . }}
    helm.sh/chart: {{ include "api-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  GATEWAY_AUTH_SECRET: {{ "super-secret-jwt-signing-key-for-api-gateway-auth-2025" | b64enc | quote }}
